version: '3.8'
services:
  app:
      build:
        context: .
        dockerfile: Dockerfile
      volumes:
        - .:/app
      environment:
        - PYTHONUNBUFFERED=1
      ports:
        - "8000:8000"
      command: poetry run python script.py
volumes:
  app:
